---
title: Область видимості
teaching: 10
exercises: 10
---

::::::::::::::::::::::::::::::::::::::: objectives

- Визначити локальні та глобальні змінні.
- Визначити параметри як локальні змінні.
- Прочитати traceback та визначити файл, функцію та номер рядка, з якого сталася помилка, тип помилки та повідомлення про помилку.

::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::: питань

- Як виклики функцій насправді працюють?
- Як я можу визначити, де виникають помилки?

::::::::::::::::::::::::::::::::::::::::::::::::::

## Межі змінної - це частина програми, яка може 'побачити' яку змінну.

- Існує тільки стільки розумних імен для змінних.
- People using functions shouldn't have to worry about
  what variable names the author of the function used.
- People writing functions shouldn't have to worry about
  what variable names the function's caller uses.
- Частина програми, в якій видима змінна називається її \* scope\*.

```python
тиск = 103.9

значення def (t): температура
    = t * 1.43 / тиск
    повернути температуру
```

- `pressure` є _глобальною_.
  - Визначено поза межами будь-якої конкретної функції.
  - Видиме всюди.
- `t` та `температура` є _місцевими змінними_ у `adjust`.
  - Визначена в функції.
  - Не відображається в головній програмі.
  - Remember: a function parameter is a variable
    that is automatically assigned a value when the function is called.

```python
print('скориговано:', adjust(0.9))
print('температура після виклику:', температура)
```

```output
скориговано: 0.01238691049085659
```

```error
Traceback (most recent call last):
  File "/Users/swcarpentry/foo.py", line 8, in <module>
    print('temperature after call:', temperature)
NameError: name 'temperature' is not defined
```

:::::::::::::::::::::::::::::::::::::::::::: виклик

## Використання локальної та глобальної змінної

Відстежувати значення всіх змінних у цій програмі оскільки вони виконуються.
(Використовуйте "---" як значення змінних до і після їх існування.)

```python
limit = 100

def clip(value):
    return min(max(0.0, value), limit)

value = -22.5
print(clip(value))
```

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::::::: виклик

## Повідомлення про помилку

Зчитати інформацію про трасування нижченаведене відео та визначити наступне:

1. Скільки рівнів має трасесія?
2. Що таке ім'я файлу, де сталася помилка?
3. Яка назва функції де відбулася помилка?
4. При якому номері рядка в цій функції виникла помилка?
5. Який тип помилки?
6. Яке повідомлення про помилку?

```error
---------------------------------------------------------------------------
KeyError Traceback (останній виклик останній)<ipython-input-2-e4c4cbafeeb5> в <module>()
      1 errors_02
----> 2 errors_02. rint_friday_message()

/Users/ghopper/thesis/code/errors_02. y print_friday_message()
     13
     14 def print_friday_message():
---> 15 print_message("П'ятниця")

/Users/ghopper/thesis/code/errors_02. y в print_message(день)
      "неділя": "Шоу, вихідні майже скінчилися.
     10 }
---> 11 print(повідомлення[day])
     12
     13

KeyError: 'П'ятниця'
```

:::::::::::::::::::: Рішення

## Розв'язок

1. Три рівні.

2. `errors_02.py`

3. `print_message`

4. Лінія 11 CPTM

5. `KeyError`. При спробі знайти ключ, який не існує (зазвичай в структурі
   на кшталт словника). Ми можемо знайти більше інформації про `KeyError` та інші вбудовані виключення
   в [документації Python.org/3/library/exceptions.html#KeyError).

6. `KeyError: 'П'ятниця'`

:::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: keypoints

- Межі змінної - це частина програми, яка може 'побачити' яку змінну.

::::::::::::::::::::::::::::::::::::::::::::::::::
